### ISSUE TITLE
Removed from asset store?

### ISSUE THREAD

**Issue by LeeLorenzSr** [Kitbashery/smart-gameobjects-issue-tracker#1]
I've seen this happen to other vendors, wondering what happened here before I use this asset in my projects

**Comment by TolinSimpson** [comment]
@LeeLorenzSr Support will still be offered through 2024. In this case, I've vastly overhauled all my commercial and open-source assets into a unified game kit. If/when the improved product reaches the asset store there will be a free upgrade to 2023 purchasers. The asset can still be downloaded but is no longer offered to new users.
